# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('cre_date', models.DateTimeField(verbose_name='date created')),
                ('deadline', models.DateTimeField(verbose_name='deadline_date')),
                ('importance', models.CharField(default=0, max_length=1)),
            ],
        ),
    ]
