# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170730_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deadline_date'),
        ),
    ]
