# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20170730_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='deadline_date'),
            preserve_default=False,
        ),
    ]
