# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cre_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
